// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzaHyaO-WVrJSQzoSOpR2fNeKFR8IaQfk',
    appId: '1:738820207445:android:d03c510470b9c2e24db5dc',
    messagingSenderId: '738820207445',
    projectId: 'satepadang-545c4',
    storageBucket: 'satepadang-545c4.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmoaYboV8FHKZAblUjsOQ5Eqi9OFTZs1w',
    appId: '1:738820207445:web:0130935ae0de72534db5dc',
    messagingSenderId: '738820207445',
    projectId: 'satepadang-545c4',
    authDomain: 'satepadang-545c4.firebaseapp.com',
    storageBucket: 'satepadang-545c4.firebasestorage.app',
    measurementId: 'G-FMY6JV9CWR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIH8YUrEo-NF9FVCfO833L3VS9YQWesT4',
    appId: '1:738820207445:ios:22ee481adab575494db5dc',
    messagingSenderId: '738820207445',
    projectId: 'satepadang-545c4',
    storageBucket: 'satepadang-545c4.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIH8YUrEo-NF9FVCfO833L3VS9YQWesT4',
    appId: '1:738820207445:ios:22ee481adab575494db5dc',
    messagingSenderId: '738820207445',
    projectId: 'satepadang-545c4',
    storageBucket: 'satepadang-545c4.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmoaYboV8FHKZAblUjsOQ5Eqi9OFTZs1w',
    appId: '1:738820207445:web:dc8acba4a955296b4db5dc',
    messagingSenderId: '738820207445',
    projectId: 'satepadang-545c4',
    authDomain: 'satepadang-545c4.firebaseapp.com',
    storageBucket: 'satepadang-545c4.firebasestorage.app',
    measurementId: 'G-HYGK94TB3H',
  );

}